# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4e9be8f89b3292dc175c1522a6a78e4cf8067edf4452939521263f30d6f28e0bb6b45d0e38368a314f5466a23cbe568712ff7bdb204f5d5f42282269423ad1

test:
  secret_key_base: a2e51e34e43dbf143e703164809e1b64f46961a85de66fefd7d1eb6d693a0363cc956296f38374d5734d26f1c3463b5589bd4239c65b9ecb271b1186b2043c81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
